apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry-ui-test-service
  namespace: krakend-test-prj
  labels:
    app: apicurio-registry-ui-test
spec:
  selector:
    app: apicurio-registry-ui-test
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8080
      nodePort: 31655
  type: NodePort
