apiVersion: v1
kind: Service
metadata:
  name: apicurio-test-registry
  namespace: krakend-test-prj
  labels:
    app: apicurio-test-registry
spec:
  selector:
    app: apicurio-test-registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31855
  type: NodePort
