apiVersion: v1
kind: Service
metadata:
  name: keycloak-test-service
  namespace: krakend-test-prj
  labels:
    app: keycloak-test
spec:
  selector:
    app: keycloak-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31440
  type: NodePort
