apiVersion: v1
kind: Service
metadata:
  name: massilgateway-test-service
  namespace: krakend-test-prj
  labels:
    app: massilgateway-test
spec:
  selector:
    app: massilgateway-test
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 31744
  type: NodePort