apiVersion: apps/v1
kind: Deployment
metadata:
  name: massilgateway-test-dep-file
  namespace: krakend-test-prj
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: massilgateway-test
  template:
    metadata:
      labels:
        app: massilgateway-test
    spec:
      containers:
        - name: massilgateway-test
          image: harbor.massiltech.com/krakendproject/test-backend-img/massilgateway4.0:17.0
          ports:
            - containerPort: 8082
          env:
            - name: DOCKER_HOST
              value: "tcp://10.175.1.110:2375"
