apiVersion: v1
kind: Service
metadata:
  name: publisher-portal-test-service
  namespace: krakend-test-prj
  labels:
    app: publisher-portal-test
spec:
  selector:
    app: publisher-portal-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30825
  type: NodePort
