apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-portal-test-deployment
  namespace: krakend-test-prj
  labels:
    app: publisher-portal-test
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: publisher-portal-test
  template:
    metadata:
      labels:
        app: publisher-portal-test
    spec:
      containers:
        - name: publisher-portal-test
          image: harbor.massiltech.com/krakendproject/test-publisher-img/publisherportal:5.8
          imagePullPolicy: Always
          ports:
            - containerPort: 80
