apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-test-pv
  namespace: krakend-test-prj
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/keycloak-data # Replace with a valid path on your node
